# Generated by Django 5.2.6 on 2025-09-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="core.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
                ("original", models.TextField()),
                ("romanized", models.TextField(blank=True, null=True)),
                ("translation_en", models.TextField()),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.song",
                    ),
                ),
            ],
            options={
                "ordering": ["no"],
            },
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                fields=("artist", "title"), name="unique_song_per_artist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("song", "no")},
        ),
    ]
