# Generated by Django 5.2.6 on 2025-09-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="song",
            name="unique_song_per_artist",
        ),
        migrations.AddField(
            model_name="artist",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="artist",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.artist"
            ),
        ),
    ]
