# Generated by Django 5.2.6 on 2025-09-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_song_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
