# Generated by Django 5.2.6 on 2025-09-30 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_artistcomment_songcomment_userprofile_artistrating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("unique_ips", models.IntegerField(default=0)),
                ("registered_user_views", models.IntegerField(default=0)),
                ("anonymous_views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Site Statistics",
                "verbose_name_plural": "Site Statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("song", "Song"),
                            ("artist", "Artist"),
                            ("album", "Album"),
                            ("home", "Home"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("content_id", models.IntegerField(blank=True, null=True)),
                ("content_title", models.CharField(blank=True, max_length=500)),
                ("url", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["-viewed_at"], name="core_pagevi_viewed__c68f15_idx"
                    ),
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="core_pagevi_content_90a8c1_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="core_pagevi_ip_addr_9bba41_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="core_pagevi_session_3251c9_idx"
                    ),
                ],
            },
        ),
    ]
