# Generated by Django 5.2.6 on 2025-10-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_album_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="album_images/"),
        ),
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="song_images/"),
        ),
    ]
