# Generated by Django 5.2.6 on 2025-10-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_album_image_song_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Or provide an image URL instead of uploading",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Or provide an image URL instead of uploading",
                null=True,
            ),
        ),
    ]
