# Generated by Django 5.2.6 on 2025-10-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_album_image_url_song_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="additional_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional artists on this album",
                related_name="collab_albums",
                to="core.artist",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                help_text="Primary artist",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="core.artist",
            ),
        ),
    ]
