# Generated by Django 5.2.6 on 2025-10-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_album_additional_artists_alter_album_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="additional_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional primary artists (not features)",
                related_name="collab_songs",
                to="core.artist",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                help_text="Primary artist",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_songs",
                to="core.artist",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="featured_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Featured artists (e.g., 'feat. Artist')",
                related_name="featured_songs",
                to="core.artist",
            ),
        ),
    ]
